version = 1

exclude_patterns = [
  "# dependencies",
  "**/node_modules",
  "/.pnp",
  ".pnp.js",
  "# testing",
  "/coverage",
  "# production",
  "**/build",
  "# misc",
  ".DS_Store",
  ".env.local",
  ".env.development.local",
  ".env.test.local",
  ".env.production.local",
  "# debug logs",
  "npm-debug.log*",
  "yarn-debug.log*",
  "yarn-error.log*",
  "# Visual Studio Code settings",
  "/.vscode",
  "# ES Lint",
  ".eslintcache",
  "# environment variables",
  ".env"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true